=== Marmioni/sitio_web_la_doc/.astro/collections/books.schema.json
{
  "$ref": "#/definitions/books",
  "definitions": {
    "books": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "Book",
            "Short Story"
          ]
        },
        "year": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "kind",
        "year",
        "description"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Marmioni/sitio_web_la_doc/src/content/books/placeholder-story-7.json
{
  "title": "Mi Crush",
  "kind": "Short Story",
  "year": "2026",
  "description": "Pero yo aceleré porque venía medio peda y me fui directo a la zanja. Entonces llegó el rescate en forma de una mano que abrió la puerta y luego me tomó en sus brazos. En ese momento me enamoré",
  "url": "https://open.substack.com/pub/marmioni/p/mi-crush?r=5lxmvs&utm_campaign=post-expanded-share&utm_medium=web"
}

=== Marmioni/sitio_web_la_doc/src/content/books/placeholder-story-3.json
{
  "title": "Ex Convicta",
  "kind": "Short Story",
  "year": "2026",
  "description": "Pieza ganadora del segundo premio del Concurso del Escritor de Substack, con el tema “pequeños placeres”",
  "url": "https://open.substack.com/pub/marmioni/p/ex-convicta?r=5lxmvs&utm_campaign=post&utm_medium=web"
}

=== Marmioni/sitio_web_la_doc/src/content/books/placeholder-story-6.json
{
  "title": "El pepino y el chorizo",
  "kind": "Short Story",
  "year": "2024",
  "description": "Un pepino y un chorizo se pelean a ver quien es el nuevo rey del barrio. La doc sale encuerada en aparicion especial de la pagina 5 a la 75.",
  "url": "https://yourname.substack.com/p/placeholder-story-5"
}
